-- MySQL Script generated by MySQL Workbench
-- Fri Nov  4 16:49:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tpi_dabd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tpi_dabd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tpi_dabd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tpi_dabd` ;

-- -----------------------------------------------------
-- Table `tpi_dabd`.`cartas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_dabd`.`cartas` (
  `id` VARCHAR(5) NOT NULL,
  `carta` VARCHAR(25) NULL DEFAULT NULL,
  `valor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tpi_dabd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_dabd`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NULL DEFAULT NULL,
  `pass` VARCHAR(50) NULL DEFAULT NULL,
  `ganadasJugador` INT NULL DEFAULT NULL,
  `ganadasCroupier` INT NULL DEFAULT NULL,
  `blackJackJugador` INT NULL DEFAULT NULL,
  `blackJackCroupier` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tpi_dabd`.`cartas_croupier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_dabd`.`cartas_croupier` (
  `codCroupier` INT NOT NULL AUTO_INCREMENT,
  `idCarta` VARCHAR(5) NULL DEFAULT NULL,
  `idUsuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codCroupier`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  INDEX `idCarta` (`idCarta` ASC) VISIBLE,
  CONSTRAINT `cartas_croupier_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `tpi_dabd`.`usuarios` (`idUsuario`),
  CONSTRAINT `cartas_croupier_ibfk_2`
    FOREIGN KEY (`idCarta`)
    REFERENCES `tpi_dabd`.`cartas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 297
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tpi_dabd`.`cartas_jugadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_dabd`.`cartas_jugadas` (
  `codJugadas` INT NOT NULL AUTO_INCREMENT,
  `idCarta` VARCHAR(5) NULL DEFAULT NULL,
  `idUsuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codJugadas`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  INDEX `idCarta` (`idCarta` ASC) VISIBLE,
  CONSTRAINT `cartas_jugadas_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `tpi_dabd`.`usuarios` (`idUsuario`),
  CONSTRAINT `cartas_jugadas_ibfk_2`
    FOREIGN KEY (`idCarta`)
    REFERENCES `tpi_dabd`.`cartas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 649
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tpi_dabd`.`cartas_jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_dabd`.`cartas_jugador` (
  `codJugador` INT NOT NULL AUTO_INCREMENT,
  `idCarta` VARCHAR(5) NULL DEFAULT NULL,
  `idUsuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codJugador`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  INDEX `idCarta` (`idCarta` ASC) VISIBLE,
  CONSTRAINT `cartas_jugador_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `tpi_dabd`.`usuarios` (`idUsuario`),
  CONSTRAINT `cartas_jugador_ibfk_2`
    FOREIGN KEY (`idCarta`)
    REFERENCES `tpi_dabd`.`cartas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 370
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tpi_dabd`.`cartas_sin_jugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_dabd`.`cartas_sin_jugar` (
  `codSinJugar` INT NOT NULL AUTO_INCREMENT,
  `idCarta` VARCHAR(5) NULL DEFAULT NULL,
  `idUsuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codSinJugar`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  INDEX `idCarta` (`idCarta` ASC) VISIBLE,
  CONSTRAINT `cartas_sin_jugar_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `tpi_dabd`.`usuarios` (`idUsuario`),
  CONSTRAINT `cartas_sin_jugar_ibfk_2`
    FOREIGN KEY (`idCarta`)
    REFERENCES `tpi_dabd`.`cartas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1459
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tpi_dabd`.`sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_dabd`.`sesiones` (
  `idSesion` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idSesion`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `sesiones_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `tpi_dabd`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `tpi_dabd` ;

-- -----------------------------------------------------
-- Placeholder table for view `tpi_dabd`.`reportesesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_dabd`.`reportesesion` (`usuario` INT, `Cantidad` INT);

-- -----------------------------------------------------
-- View `tpi_dabd`.`reportesesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpi_dabd`.`reportesesion`;
USE `tpi_dabd`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `tpi_dabd`.`reportesesion` AS select `u`.`usuario` AS `usuario`,count(`s`.`idSesion`) AS `Cantidad` from (`tpi_dabd`.`sesiones` `s` join `tpi_dabd`.`usuarios` `u` on((`s`.`idUsuario` = `u`.`idUsuario`))) group by `s`.`idUsuario`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
